version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.20.2
    working_directory: ~/repo

    steps:
      - checkout
      - run: 
          name: clean cache
          command: npm cache clean --force
      # - run:
      #     name: Install Dependencies
      #     command: npm install
      # - run:
      #     name: install
      #     command: npm ci
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: npm run-script build

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # - save_cache:
      #     paths:
      #       - node_modules
      #       - ~/.npm
      #       - ~/.cache
      #     key: v1-dependencies-{{ checksum "package.json" }}
      - store_artifacts:
          path: build/static/
          destination: BuildResult

  deploy:
    docker:
      - image: circleci/node:12.20.2
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: 
            git clone https://thangnldse62897:Th@ng26121998@git.heroku.com/simple-view-detail-reactjs-app.git
            git push https://heroku:58b7661a-6f18-4d28-8853-096cd5da7138@git.heroku.com/simple-view-detail-reactjs-app.git main


workflows:
  version: 2.1
  workflow:
    jobs:
      # - build
      - deploy

