version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install  Node.js 12.20.2 with build in nvm tool
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install v12.20.2 && nvm use v12.20.2 && nvm alias default v12.20.2
            node -v
      - run:
          name: Install nvm 
          command:  |
            $NVM_DIR/nvm.sh
            nvm alias default v12.20.2
      - run:
          name: check nvm
          command: ls -a 
      - run:
          name: Check node version
          command: |
            node -v
      - run: 
          name: clean cache
          command: npm cache clean --force
      # - run:
      #     name: Install Dependencies
      #     command: npm install
      # - run:
      #     name: install
      #     command: npm ci
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: npm run-script build

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # - save_cache:
      #     paths:
      #       - node_modules
      #       - ~/.npm
      #       - ~/.cache
      #     key: v1-dependencies-{{ checksum "package.json" }}
      - store_artifacts:
          path: build/static/
          destination: BuildResult

  deploy:
    docker:
      - image: circleci/node:12.20.2
    working_directory: ~/repo
    steps:
      - checkout
      # - run: |-
      #     cat >> ~/.netrc \<<EOF
      #       machine api.heroku.com
      #         login thangnldse62897@fpt.edu.vn
      #         password Th@ng26121998
      #       machine git.heroku.com
      #         login thangnldse62897@fpt.edu.vn
      #         password Th@ng26121998
      #     EOF
      # - run: chmod 600 ~/.netrc 

      # - run:
      #     name: Pull from Heroku
      #     command: |
      #       git config --global user.email "thangnldse62897@fpt.edu.vn"
      #       git pull https://heroku:a8f4f414-8b90-4f3a-aa4d-6dc7e35fceae@git.heroku.com/simple-view-detail-reactjs-app.git main
      - run:
          name: Deploy Master to Heroku
          command: | 
            heroku create
            git push heroku main
            heroku open
            git push origin https://heroku:a8f4f414-8b90-4f3a-aa4d-6dc7e35fceae@git.heroku.com/simple-view-detail-reactjs-app.git main

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
      # - deploy

